// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Module.proto

#ifndef PROTOBUF_INCLUDED_Module_2eproto
#define PROTOBUF_INCLUDED_Module_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "AuxData.pb.h"
#include "ProxyBlock.pb.h"
#include "Section.pb.h"
#include "Symbol.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Module_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_Module_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_Module_2eproto();
namespace gtirb {
namespace proto {
class Module;
class ModuleDefaultTypeInternal;
extern ModuleDefaultTypeInternal _Module_default_instance_;
class Module_AuxDataEntry_DoNotUse;
class Module_AuxDataEntry_DoNotUseDefaultTypeInternal;
extern Module_AuxDataEntry_DoNotUseDefaultTypeInternal _Module_AuxDataEntry_DoNotUse_default_instance_;
}  // namespace proto
}  // namespace gtirb
namespace google {
namespace protobuf {
template<> ::gtirb::proto::Module* Arena::CreateMaybeMessage<::gtirb::proto::Module>(Arena*);
template<> ::gtirb::proto::Module_AuxDataEntry_DoNotUse* Arena::CreateMaybeMessage<::gtirb::proto::Module_AuxDataEntry_DoNotUse>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace gtirb {
namespace proto {

enum FileFormat {
  Format_Undefined = 0,
  COFF = 1,
  ELF = 2,
  PE = 3,
  IdaProDb32 = 4,
  IdaProDb64 = 5,
  XCOFF = 6,
  MACHO = 7,
  RAW = 8,
  FileFormat_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::google::protobuf::int32>::min(),
  FileFormat_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::google::protobuf::int32>::max()
};
bool FileFormat_IsValid(int value);
const FileFormat FileFormat_MIN = Format_Undefined;
const FileFormat FileFormat_MAX = RAW;
const int FileFormat_ARRAYSIZE = FileFormat_MAX + 1;

const ::google::protobuf::EnumDescriptor* FileFormat_descriptor();
inline const ::std::string& FileFormat_Name(FileFormat value) {
  return ::google::protobuf::internal::NameOfEnum(
    FileFormat_descriptor(), value);
}
inline bool FileFormat_Parse(
    const ::std::string& name, FileFormat* value) {
  return ::google::protobuf::internal::ParseNamedEnum<FileFormat>(
    FileFormat_descriptor(), name, value);
}
enum ISA {
  ISA_Undefined = 0,
  IA32 = 1,
  PPC32 = 2,
  X64 = 3,
  ARM = 4,
  ValidButUnsupported = 5,
  PPC64 = 6,
  ARM64 = 7,
  MIPS32 = 8,
  MIPS64 = 9,
  ISA_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::google::protobuf::int32>::min(),
  ISA_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::google::protobuf::int32>::max()
};
bool ISA_IsValid(int value);
const ISA ISA_MIN = ISA_Undefined;
const ISA ISA_MAX = MIPS64;
const int ISA_ARRAYSIZE = ISA_MAX + 1;

const ::google::protobuf::EnumDescriptor* ISA_descriptor();
inline const ::std::string& ISA_Name(ISA value) {
  return ::google::protobuf::internal::NameOfEnum(
    ISA_descriptor(), value);
}
inline bool ISA_Parse(
    const ::std::string& name, ISA* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ISA>(
    ISA_descriptor(), name, value);
}
// ===================================================================

class Module_AuxDataEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<Module_AuxDataEntry_DoNotUse, 
    ::std::string, ::gtirb::proto::AuxData,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > {
public:
#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
static bool _ParseMap(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  typedef ::google::protobuf::internal::MapEntry<Module_AuxDataEntry_DoNotUse, 
    ::std::string, ::gtirb::proto::AuxData,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > SuperType;
  Module_AuxDataEntry_DoNotUse();
  Module_AuxDataEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const Module_AuxDataEntry_DoNotUse& other);
  static const Module_AuxDataEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const Module_AuxDataEntry_DoNotUse*>(&_Module_AuxDataEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class Module final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gtirb.proto.Module) */ {
 public:
  Module();
  virtual ~Module();

  Module(const Module& from);

  inline Module& operator=(const Module& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Module(Module&& from) noexcept
    : Module() {
    *this = ::std::move(from);
  }

  inline Module& operator=(Module&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Module& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Module* internal_default_instance() {
    return reinterpret_cast<const Module*>(
               &_Module_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(Module* other);
  friend void swap(Module& a, Module& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Module* New() const final {
    return CreateMaybeMessage<Module>(nullptr);
  }

  Module* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Module>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Module& from);
  void MergeFrom(const Module& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Module* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // repeated .gtirb.proto.Symbol symbols = 9;
  int symbols_size() const;
  void clear_symbols();
  static const int kSymbolsFieldNumber = 9;
  ::gtirb::proto::Symbol* mutable_symbols(int index);
  ::google::protobuf::RepeatedPtrField< ::gtirb::proto::Symbol >*
      mutable_symbols();
  const ::gtirb::proto::Symbol& symbols(int index) const;
  ::gtirb::proto::Symbol* add_symbols();
  const ::google::protobuf::RepeatedPtrField< ::gtirb::proto::Symbol >&
      symbols() const;

  // repeated .gtirb.proto.Section sections = 12;
  int sections_size() const;
  void clear_sections();
  static const int kSectionsFieldNumber = 12;
  ::gtirb::proto::Section* mutable_sections(int index);
  ::google::protobuf::RepeatedPtrField< ::gtirb::proto::Section >*
      mutable_sections();
  const ::gtirb::proto::Section& sections(int index) const;
  ::gtirb::proto::Section* add_sections();
  const ::google::protobuf::RepeatedPtrField< ::gtirb::proto::Section >&
      sections() const;

  // repeated .gtirb.proto.ProxyBlock proxies = 16;
  int proxies_size() const;
  void clear_proxies();
  static const int kProxiesFieldNumber = 16;
  ::gtirb::proto::ProxyBlock* mutable_proxies(int index);
  ::google::protobuf::RepeatedPtrField< ::gtirb::proto::ProxyBlock >*
      mutable_proxies();
  const ::gtirb::proto::ProxyBlock& proxies(int index) const;
  ::gtirb::proto::ProxyBlock* add_proxies();
  const ::google::protobuf::RepeatedPtrField< ::gtirb::proto::ProxyBlock >&
      proxies() const;

  // map<string, .gtirb.proto.AuxData> aux_data = 17;
  int aux_data_size() const;
  void clear_aux_data();
  static const int kAuxDataFieldNumber = 17;
  const ::google::protobuf::Map< ::std::string, ::gtirb::proto::AuxData >&
      aux_data() const;
  ::google::protobuf::Map< ::std::string, ::gtirb::proto::AuxData >*
      mutable_aux_data();

  // bytes uuid = 1;
  void clear_uuid();
  static const int kUuidFieldNumber = 1;
  const ::std::string& uuid() const;
  void set_uuid(const ::std::string& value);
  #if LANG_CXX11
  void set_uuid(::std::string&& value);
  #endif
  void set_uuid(const char* value);
  void set_uuid(const void* value, size_t size);
  ::std::string* mutable_uuid();
  ::std::string* release_uuid();
  void set_allocated_uuid(::std::string* uuid);

  // string binary_path = 2;
  void clear_binary_path();
  static const int kBinaryPathFieldNumber = 2;
  const ::std::string& binary_path() const;
  void set_binary_path(const ::std::string& value);
  #if LANG_CXX11
  void set_binary_path(::std::string&& value);
  #endif
  void set_binary_path(const char* value);
  void set_binary_path(const char* value, size_t size);
  ::std::string* mutable_binary_path();
  ::std::string* release_binary_path();
  void set_allocated_binary_path(::std::string* binary_path);

  // string name = 7;
  void clear_name();
  static const int kNameFieldNumber = 7;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // bytes entry_point = 18;
  void clear_entry_point();
  static const int kEntryPointFieldNumber = 18;
  const ::std::string& entry_point() const;
  void set_entry_point(const ::std::string& value);
  #if LANG_CXX11
  void set_entry_point(::std::string&& value);
  #endif
  void set_entry_point(const char* value);
  void set_entry_point(const void* value, size_t size);
  ::std::string* mutable_entry_point();
  ::std::string* release_entry_point();
  void set_allocated_entry_point(::std::string* entry_point);

  // uint64 preferred_addr = 3;
  void clear_preferred_addr();
  static const int kPreferredAddrFieldNumber = 3;
  ::google::protobuf::uint64 preferred_addr() const;
  void set_preferred_addr(::google::protobuf::uint64 value);

  // int64 rebase_delta = 4;
  void clear_rebase_delta();
  static const int kRebaseDeltaFieldNumber = 4;
  ::google::protobuf::int64 rebase_delta() const;
  void set_rebase_delta(::google::protobuf::int64 value);

  // .gtirb.proto.FileFormat file_format = 5;
  void clear_file_format();
  static const int kFileFormatFieldNumber = 5;
  ::gtirb::proto::FileFormat file_format() const;
  void set_file_format(::gtirb::proto::FileFormat value);

  // .gtirb.proto.ISA isa = 6;
  void clear_isa();
  static const int kIsaFieldNumber = 6;
  ::gtirb::proto::ISA isa() const;
  void set_isa(::gtirb::proto::ISA value);

  // @@protoc_insertion_point(class_scope:gtirb.proto.Module)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::gtirb::proto::Symbol > symbols_;
  ::google::protobuf::RepeatedPtrField< ::gtirb::proto::Section > sections_;
  ::google::protobuf::RepeatedPtrField< ::gtirb::proto::ProxyBlock > proxies_;
  ::google::protobuf::internal::MapField<
      Module_AuxDataEntry_DoNotUse,
      ::std::string, ::gtirb::proto::AuxData,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > aux_data_;
  ::google::protobuf::internal::ArenaStringPtr uuid_;
  ::google::protobuf::internal::ArenaStringPtr binary_path_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr entry_point_;
  ::google::protobuf::uint64 preferred_addr_;
  ::google::protobuf::int64 rebase_delta_;
  int file_format_;
  int isa_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Module_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Module

// bytes uuid = 1;
inline void Module::clear_uuid() {
  uuid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Module::uuid() const {
  // @@protoc_insertion_point(field_get:gtirb.proto.Module.uuid)
  return uuid_.GetNoArena();
}
inline void Module::set_uuid(const ::std::string& value) {
  
  uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gtirb.proto.Module.uuid)
}
#if LANG_CXX11
inline void Module::set_uuid(::std::string&& value) {
  
  uuid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:gtirb.proto.Module.uuid)
}
#endif
inline void Module::set_uuid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gtirb.proto.Module.uuid)
}
inline void Module::set_uuid(const void* value, size_t size) {
  
  uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gtirb.proto.Module.uuid)
}
inline ::std::string* Module::mutable_uuid() {
  
  // @@protoc_insertion_point(field_mutable:gtirb.proto.Module.uuid)
  return uuid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Module::release_uuid() {
  // @@protoc_insertion_point(field_release:gtirb.proto.Module.uuid)
  
  return uuid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Module::set_allocated_uuid(::std::string* uuid) {
  if (uuid != nullptr) {
    
  } else {
    
  }
  uuid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), uuid);
  // @@protoc_insertion_point(field_set_allocated:gtirb.proto.Module.uuid)
}

// string binary_path = 2;
inline void Module::clear_binary_path() {
  binary_path_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Module::binary_path() const {
  // @@protoc_insertion_point(field_get:gtirb.proto.Module.binary_path)
  return binary_path_.GetNoArena();
}
inline void Module::set_binary_path(const ::std::string& value) {
  
  binary_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gtirb.proto.Module.binary_path)
}
#if LANG_CXX11
inline void Module::set_binary_path(::std::string&& value) {
  
  binary_path_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:gtirb.proto.Module.binary_path)
}
#endif
inline void Module::set_binary_path(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  binary_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gtirb.proto.Module.binary_path)
}
inline void Module::set_binary_path(const char* value, size_t size) {
  
  binary_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gtirb.proto.Module.binary_path)
}
inline ::std::string* Module::mutable_binary_path() {
  
  // @@protoc_insertion_point(field_mutable:gtirb.proto.Module.binary_path)
  return binary_path_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Module::release_binary_path() {
  // @@protoc_insertion_point(field_release:gtirb.proto.Module.binary_path)
  
  return binary_path_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Module::set_allocated_binary_path(::std::string* binary_path) {
  if (binary_path != nullptr) {
    
  } else {
    
  }
  binary_path_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), binary_path);
  // @@protoc_insertion_point(field_set_allocated:gtirb.proto.Module.binary_path)
}

// uint64 preferred_addr = 3;
inline void Module::clear_preferred_addr() {
  preferred_addr_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Module::preferred_addr() const {
  // @@protoc_insertion_point(field_get:gtirb.proto.Module.preferred_addr)
  return preferred_addr_;
}
inline void Module::set_preferred_addr(::google::protobuf::uint64 value) {
  
  preferred_addr_ = value;
  // @@protoc_insertion_point(field_set:gtirb.proto.Module.preferred_addr)
}

// int64 rebase_delta = 4;
inline void Module::clear_rebase_delta() {
  rebase_delta_ = PROTOBUF_LONGLONG(0);
}
inline ::google::protobuf::int64 Module::rebase_delta() const {
  // @@protoc_insertion_point(field_get:gtirb.proto.Module.rebase_delta)
  return rebase_delta_;
}
inline void Module::set_rebase_delta(::google::protobuf::int64 value) {
  
  rebase_delta_ = value;
  // @@protoc_insertion_point(field_set:gtirb.proto.Module.rebase_delta)
}

// .gtirb.proto.FileFormat file_format = 5;
inline void Module::clear_file_format() {
  file_format_ = 0;
}
inline ::gtirb::proto::FileFormat Module::file_format() const {
  // @@protoc_insertion_point(field_get:gtirb.proto.Module.file_format)
  return static_cast< ::gtirb::proto::FileFormat >(file_format_);
}
inline void Module::set_file_format(::gtirb::proto::FileFormat value) {
  
  file_format_ = value;
  // @@protoc_insertion_point(field_set:gtirb.proto.Module.file_format)
}

// .gtirb.proto.ISA isa = 6;
inline void Module::clear_isa() {
  isa_ = 0;
}
inline ::gtirb::proto::ISA Module::isa() const {
  // @@protoc_insertion_point(field_get:gtirb.proto.Module.isa)
  return static_cast< ::gtirb::proto::ISA >(isa_);
}
inline void Module::set_isa(::gtirb::proto::ISA value) {
  
  isa_ = value;
  // @@protoc_insertion_point(field_set:gtirb.proto.Module.isa)
}

// string name = 7;
inline void Module::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Module::name() const {
  // @@protoc_insertion_point(field_get:gtirb.proto.Module.name)
  return name_.GetNoArena();
}
inline void Module::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gtirb.proto.Module.name)
}
#if LANG_CXX11
inline void Module::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:gtirb.proto.Module.name)
}
#endif
inline void Module::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gtirb.proto.Module.name)
}
inline void Module::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gtirb.proto.Module.name)
}
inline ::std::string* Module::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:gtirb.proto.Module.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Module::release_name() {
  // @@protoc_insertion_point(field_release:gtirb.proto.Module.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Module::set_allocated_name(::std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:gtirb.proto.Module.name)
}

// repeated .gtirb.proto.Symbol symbols = 9;
inline int Module::symbols_size() const {
  return symbols_.size();
}
inline ::gtirb::proto::Symbol* Module::mutable_symbols(int index) {
  // @@protoc_insertion_point(field_mutable:gtirb.proto.Module.symbols)
  return symbols_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::gtirb::proto::Symbol >*
Module::mutable_symbols() {
  // @@protoc_insertion_point(field_mutable_list:gtirb.proto.Module.symbols)
  return &symbols_;
}
inline const ::gtirb::proto::Symbol& Module::symbols(int index) const {
  // @@protoc_insertion_point(field_get:gtirb.proto.Module.symbols)
  return symbols_.Get(index);
}
inline ::gtirb::proto::Symbol* Module::add_symbols() {
  // @@protoc_insertion_point(field_add:gtirb.proto.Module.symbols)
  return symbols_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::gtirb::proto::Symbol >&
Module::symbols() const {
  // @@protoc_insertion_point(field_list:gtirb.proto.Module.symbols)
  return symbols_;
}

// repeated .gtirb.proto.ProxyBlock proxies = 16;
inline int Module::proxies_size() const {
  return proxies_.size();
}
inline ::gtirb::proto::ProxyBlock* Module::mutable_proxies(int index) {
  // @@protoc_insertion_point(field_mutable:gtirb.proto.Module.proxies)
  return proxies_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::gtirb::proto::ProxyBlock >*
Module::mutable_proxies() {
  // @@protoc_insertion_point(field_mutable_list:gtirb.proto.Module.proxies)
  return &proxies_;
}
inline const ::gtirb::proto::ProxyBlock& Module::proxies(int index) const {
  // @@protoc_insertion_point(field_get:gtirb.proto.Module.proxies)
  return proxies_.Get(index);
}
inline ::gtirb::proto::ProxyBlock* Module::add_proxies() {
  // @@protoc_insertion_point(field_add:gtirb.proto.Module.proxies)
  return proxies_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::gtirb::proto::ProxyBlock >&
Module::proxies() const {
  // @@protoc_insertion_point(field_list:gtirb.proto.Module.proxies)
  return proxies_;
}

// repeated .gtirb.proto.Section sections = 12;
inline int Module::sections_size() const {
  return sections_.size();
}
inline ::gtirb::proto::Section* Module::mutable_sections(int index) {
  // @@protoc_insertion_point(field_mutable:gtirb.proto.Module.sections)
  return sections_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::gtirb::proto::Section >*
Module::mutable_sections() {
  // @@protoc_insertion_point(field_mutable_list:gtirb.proto.Module.sections)
  return &sections_;
}
inline const ::gtirb::proto::Section& Module::sections(int index) const {
  // @@protoc_insertion_point(field_get:gtirb.proto.Module.sections)
  return sections_.Get(index);
}
inline ::gtirb::proto::Section* Module::add_sections() {
  // @@protoc_insertion_point(field_add:gtirb.proto.Module.sections)
  return sections_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::gtirb::proto::Section >&
Module::sections() const {
  // @@protoc_insertion_point(field_list:gtirb.proto.Module.sections)
  return sections_;
}

// map<string, .gtirb.proto.AuxData> aux_data = 17;
inline int Module::aux_data_size() const {
  return aux_data_.size();
}
inline const ::google::protobuf::Map< ::std::string, ::gtirb::proto::AuxData >&
Module::aux_data() const {
  // @@protoc_insertion_point(field_map:gtirb.proto.Module.aux_data)
  return aux_data_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::gtirb::proto::AuxData >*
Module::mutable_aux_data() {
  // @@protoc_insertion_point(field_mutable_map:gtirb.proto.Module.aux_data)
  return aux_data_.MutableMap();
}

// bytes entry_point = 18;
inline void Module::clear_entry_point() {
  entry_point_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Module::entry_point() const {
  // @@protoc_insertion_point(field_get:gtirb.proto.Module.entry_point)
  return entry_point_.GetNoArena();
}
inline void Module::set_entry_point(const ::std::string& value) {
  
  entry_point_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gtirb.proto.Module.entry_point)
}
#if LANG_CXX11
inline void Module::set_entry_point(::std::string&& value) {
  
  entry_point_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:gtirb.proto.Module.entry_point)
}
#endif
inline void Module::set_entry_point(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  entry_point_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gtirb.proto.Module.entry_point)
}
inline void Module::set_entry_point(const void* value, size_t size) {
  
  entry_point_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gtirb.proto.Module.entry_point)
}
inline ::std::string* Module::mutable_entry_point() {
  
  // @@protoc_insertion_point(field_mutable:gtirb.proto.Module.entry_point)
  return entry_point_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Module::release_entry_point() {
  // @@protoc_insertion_point(field_release:gtirb.proto.Module.entry_point)
  
  return entry_point_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Module::set_allocated_entry_point(::std::string* entry_point) {
  if (entry_point != nullptr) {
    
  } else {
    
  }
  entry_point_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), entry_point);
  // @@protoc_insertion_point(field_set_allocated:gtirb.proto.Module.entry_point)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace gtirb

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::gtirb::proto::FileFormat> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::gtirb::proto::FileFormat>() {
  return ::gtirb::proto::FileFormat_descriptor();
}
template <> struct is_proto_enum< ::gtirb::proto::ISA> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::gtirb::proto::ISA>() {
  return ::gtirb::proto::ISA_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_Module_2eproto
